import json
from datetime import datetime
from jinja2 import Template
from rich.console import Console

console = Console()

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AutoRecon Report - {{ target }}</title>
    <style>
        body { background:#0a0a0a; color:#00ff00; font-family:'Courier New',monospace; padding:20px; }
        h1 { color:#ff0000; text-align:center; border-bottom:2px solid #ff0000; padding-bottom:10px; }
        h2 { color:#00ffff; border-left:4px solid #00ffff; padding-left:10px; }
        .info { background:#111; padding:15px; border-radius:8px; margin:10px 0; }
        .badge { display:inline-block; padding:3px 10px; border-radius:4px; font-size:12px; }
        .found { background:#004400; color:#00ff00; }
        .missing { background:#440000; color:#ff0000; }
        table { width:100%; border-collapse:collapse; margin:10px 0; }
        th { background:#1a1a1a; color:#00ffff; padding:10px; text-align:left; }
        td { padding:8px; border-bottom:1px solid #222; }
        tr:hover { background:#111; }
        .footer { text-align:center; color:#555; margin-top:30px; font-size:12px; }
    </style>
</head>
<body>
    <h1>🔍 AutoRecon Security Report</h1>
    <div class="info">
        <p><b>Target:</b> {{ target }}</p>
        <p><b>Date:</b> {{ date }}</p>
        <p><b>Modules Run:</b> {{ modules }}</p>
    </div>
    {% for section in sections %}
    <h2>{{ section.title }}</h2>
    <div class="info">
        <pre>{{ section.content }}</pre>
    </div>
    {% endfor %}
    <div class="footer">Generated by AutoRecon Toolkit | For Educational Purposes Only</div>
</body>
</html>
"""

def generate_report(target, modules, sections, output="report"):
    console.print(f"\n[bold cyan]═══ Generating Report ═══[/bold cyan]\n")
    try:
        template = Template(HTML_TEMPLATE)
        html = template.render(
            target=target,
            date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            modules=modules,
            sections=sections
        )
        filename = f"{output}_{target}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        with open(filename, "w") as f:
            f.write(html)
        console.print(f"[bold green]✓ Report saved:[/bold green] {filename}")
    except Exception as e:
        console.print(f"[bold red]Error:[/bold red] {e}")
